#!/bin/bash

ovsdb-server /usr/local/etc/ovs-vswitchd.conf.db --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,manager_options --detach
ovs-vswitchd unix:/usr/local/var/run/openvswitch/db.sock --detach
